# Generated by Django 5.1.4 on 2024-12-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vorkers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vorkers",
            options={"verbose_name": "Работник", "verbose_name_plural": "Работники"},
        ),
    ]
